apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy99
  labels:
    app: autodeploy99
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1719458717556
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy99
  template:
    metadata:
      labels:
        app: autodeploy99
    spec:
      containers:
        - name: autodeploy99
          image: acrworkflow1719458717556.azurecr.io/image-workflow-1719458717556:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
